backend/src/main/java/com/zzang/chongdae/comment/repository/Comment.java
backend/src/main/java/com/zzang/chongdae/common/repository/BaseTimeEntity.java
backend/src/main/java/com/zzang/chongdae/member/repository/Member.java
backend/src/main/java/com/zzang/chongdae/offering/repository/Offering.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMember.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRole.java

close #9 
- 기본 도메인 추가
- offering, offering_member, member, comment

feat: 도메인 추가

---

backend/build.gradle
backend/src/main/java/com/zzang/chongdae/common/config/SwaggerConfig.java
backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/resources/application.yml

close #21 
- swagger 의존성 추가
- swagger 컨트롤러 연동

feat: API 문서화 적용

---

.github/workflows/backend-ci-cd.yml
Dockerfile

close #22 
- chore: 백엔드 CI 및 도커 파일 작성

chore: 백엔드 CI 및 도커 파일 작성

---

.github/workflows/backend-ci-cd.yml

chore: 백엔드 CD 스크립트 작성

---

.github/workflows/backend-ci-cd.yml

chore: gradle 캐싱 로직 추가

---

backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingDetailResponse.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRepository.java

close #41 
- 공모 상세 조회 API에 참여자 목록 필드 추가

feat: 공모 상세 조회 시 참여자 목록 추가

---

backend/http/offering-member.http
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingStatus.java
backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/main/resources/application.yml

close #47 
- 공모 참여 API의 불필요한 응답값 전부 제거

feat: 공모 참여 API의 불필요한 응답값 전부 제거

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentSaveRequest.java

feat: 댓글 작성 API 구현

---

backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/global/config/JpaAuditingConfig.java
backend/src/main/java/com/zzang/chongdae/global/config/SwaggerConfig.java
backend/src/main/java/com/zzang/chongdae/global/repository/entity/BaseTimeEntity.java
backend/src/main/java/com/zzang/chongdae/member/repository/entity/MemberEntity.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java

close #60 
- common 패키지명을 global로 변경

refactor: common 패키지명을 global로 변경

---

.github/workflows/android.yml

close #33 
안드로이드 CI 작업
manifest 관련 수정 필요

chore: 안드로이드 CI 파일 작성

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/comment/domain/CommentWithRole.java
backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentAllResponse.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentAllResponseItem.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentCreatedAtResponse.java
backend/src/main/java/com/zzang/chongdae/member/repository/entity/MemberEntity.java
backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMemberRole.java

feat: 댓글 목록 조회 API 구현

---

.github/workflows/android.yml
android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml

close #64 
build CI 작업을 위한 manifest 파일 수정
`<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` 추가 (API33 이상 필수)

chore: build CI 작업을 위한 manifest 파일 수정

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponse.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponseItem.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/LatestCommentResponse.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingWithRole.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java

feat: 댓글방 목록 조회 API 구현

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #71
https://github.com/user-attachments/assets/85c083cc-d7ec-4ecf-80ff-1fcdc86911e4
api 연결 바로 해야해서 빠른 확인 부탁드려용!!!!!!!!!!!!!!!!!

feat 댓글방 접히는 공지 뷰 구현

---

backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java

close #75 
- 댓글방 및 댓글 목록 조회 서비스 계층 리팩터링

refactor: 댓글방 및 댓글 목록 조회 서비스 계층

---

backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java

close #79 
- 댓글방 목록 조회 시 가장 최근 댓글 조회

fix: 댓글방 목록 조회 시 가장 최근 댓글 조회

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentLatestResponse.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentRoomAllResponseItem.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java

refactor: 댓글 도메인 코드 리팩터링

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zzang/chongdae/data/remote/api/CommentDetailApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/request/CommentRequest.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/CommentDetailDataSource.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/impl/CommentDetailDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/remote/CommentDetailRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/CommentDetailRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #68 
댓글방 댓글 작성 api 연결
https://github.com/user-attachments/assets/99b05908-0e42-4e6e-8498-7fba1ce669e5
로그인 이후 멤버 아이디 로직 수정 필요하고
edit text에서 키보드 때문에 ui 올라가는 오류도 나중에 수정할 예정입니도

feat: 댓글방 댓글 작성 api 연결

---

backend/src/main/java/com/zzang/chongdae/comment/exception/CommentErrorCode.java
backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentSaveRequest.java
backend/src/main/java/com/zzang/chongdae/global/exception/ErrorMessage.java
backend/src/main/java/com/zzang/chongdae/global/exception/ErrorResponse.java
backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/global/exception/MarketException.java
backend/src/main/java/com/zzang/chongdae/member/exception/MemberErrorCode.java
backend/src/main/java/com/zzang/chongdae/member/repository/entity/MemberEntity.java
backend/src/main/java/com/zzang/chongdae/offering/exception/OfferingErrorCode.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipationRequest.java

feat: 전반적인 예외 처리

---

backend/src/main/java/com/zzang/chongdae/global/exception/ErrorMessage.java

close #102 
- 에러메시지 필드명 변경
- value to message

refactor: 에러메시지 필드명 변경

---

backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingMemberFixture.java

fix: 댓글방 조회 테스트 수정

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
android/app/src/main/res/drawable/btn_exit.xml
android/app/src/main/res/layout/activity_comment_detail.xml
android/app/src/main/res/layout/item_my_comment.xml
android/app/src/main/res/layout/item_offering_member.xml
android/app/src/main/res/values/dimens.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/style.xml

close #135 
https://github.com/user-attachments/assets/84a8b5a2-13e6-4424-9656-d57cb972dad6
댓글방 참여자 목록 Drawer Layout view 구현
참여자 목록 item view 구현
없서용~

feat: 댓글방 참여자 목록 Drawer Layout UI 구현 

---

.github/workflows/backend-ci-cd.yml
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingAllResponseItem.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #140 
- 공모에 저장하는 주소 값 구체화

refactor: 공모에 저장하는 주소 값 구체화

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java

refactor: API 문서 개선

---

android/app/build.gradle.kts
android/build.gradle.kts

close #164 
FireBase 초기 설정(의존성 추가) 했습니다.

feat: FireBase 초기 설정

---

.github/workflows/android.yml

close #172 
google-services.json에 대한 스크립트 추가

chore: CI 스크립트 추가

---

backend/src/main/java/com/zzang/chongdae/offering/config/OfferingConfig.java
backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/JsoupHtmlCrawler.java

close #170 
- header 값 `User-Agent` 추가
- read timeout 조정 (1 --> 3초)

fix: og 태그 추출 시 크롤링 이슈 해결

---

backend/src/main/java/com/zzang/chongdae/member/service/NicknameWordInitializer.java
backend/src/main/java/com/zzang/chongdae/member/service/NicknameWordReader.java

close #181 
- nicknameWordInitializer 설정 오류를 해결합니다

fix: nicknameWordInitializer 설정 오류 해결

---

backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #183 
- keyword null일 때 처리 및 docs에서 required 제거

fix: keyword null일 때 처리 및 docs에서 required 제거

---

backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/JsoupHtmlCrawler.java

close #178 
- http header에 `Host` 헤더를 추가합니다.
- `Host` 헤더에는 `productUrl`의 host값을 파싱한 값이 들어갑니다.

fix: og 이미지 태그 크롤링 문제 해결

---

backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingAllResponseItem.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #191 
- 공모 목록 조회 응답값에 낱개가격 추가

feat: 공모 목록 조회 응답값에 낱개가격 추가

---

backend/src/main/java/com/zzang/chongdae/offering/config/OfferingConfig.java

close #194 
- OG image 크롤링 read timeout 5초로 변경합니다

chore: OG image 크롤링 read timeout 5초로 변경

---

backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingStatusResponse.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #192 
- 댓글방 상태 조회 시 상태별 이미지 함께 반환

feat: 댓글방 상태 조회 시 상태별 이미지 함께 반환

---

android/app/src/main/java/com/zzang/chongdae/data/mapper/FilterMapper.kt
android/app/src/main/java/com/zzang/chongdae/data/mapper/OfferingConditionMapper.kt
android/app/src/main/java/com/zzang/chongdae/data/mapper/OfferingMapper.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/api/OfferingApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/FiltersResponse.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteFilter.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteFilterName.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteFilterType.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteOffering.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteOfferingCondition.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/OfferingRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/offering/OfferingRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/Filter.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/FilterName.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/FilterType.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/Offering.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/OfferingCondition.kt
android/app/src/main/java/com/zzang/chongdae/domain/paging/OfferingPagingSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnFilterClickListener.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingViewHolder.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/layout/item_offering.xml
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/strings.xml

close #176 
- 검색 기능 구현
- 필터링 기능 구현
- 참여가능만 필터는 구현이 되어있지 않아 동작하지 않도록 했습니다.
- 필터 중복 적용또한 구현이 되어있지 않아 추후 서버에서 구현되는 대로 추가하겠습니다.
https://github.com/user-attachments/assets/1be7d3d6-1793-4442-96be-733bf84ca8a6

feat: 공모 목록 조회 API연결

---

backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java

close #205 
- 공모 글 작성 시 총대 참여자 추가

refactor: 공모 글 작성 시 총대 참여자 추가

---

android/app/src/main/AndroidManifest.xml

close #203 
키보드가 올라올 때 바텀네비게이션까지 올라오는 부분 수정했습니다.
https://github.com/user-attachments/assets/f52a1080-2c27-47ef-a070-12e255a4c11b

feat: 바텀네비게이션 고정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zzang/chongdae/data/mapper/OfferingMapper.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/RemoteOffering.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/MainActivity.kt

close #204 
키보드 이외 영역 터치 시 키보드 내려가도록 구현하였습니다.
https://github.com/user-attachments/assets/ccaa8552-3518-44d1-867b-79b00e79e5ec

feat: 키보드 이외 영역 터치 시 키보드 내려가도록 구현

---

backend/http/auth.http
backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
backend/src/main/java/com/zzang/chongdae/auth/controller/CookieConsumer.java
backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/LoginResponse.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/RefreshRequest.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/RefreshResponse.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupMemberDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupOutput.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupResponse.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupResponseDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupTokenResponseItem.java
backend/src/test/java/com/zzang/chongdae/auth/integration/AuthIntegrationTest.java

close #224 
- 토큰 재발급 API에서 requestHeader로 refreshToken 받도록 수정

feat: 토큰 재발급 API에서 requestHeader로 refreshToken 받도록 수정

---

backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingStatusResponse.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #228 
- 댓글방 상태 조회 시 버튼 텍스트 추가

feat: 댓글방 상태 조회 시 버튼 텍스트 추가

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/OfferingApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/OfferingRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/offering/OfferingRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #218 
댓글방 상태를 변경한다.
https://github.com/user-attachments/assets/07e40d92-1f55-4515-b737-b74a231ad10a
얘도 특이사항 없습니도

feat: 댓글방 상태 변경

---

android/app/src/main/java/com/zzang/chongdae/domain/paging/OfferingPagingSource.kt

fix: 필터링 기능 버그 수정

---

android/app/build.gradle.kts
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/home/OfferingViewModelTest.kt
android/app/src/test/java/com/zzang/chongdae/util/TestFixture.kt

close #253 
홈화면 테스트 작성
mockk의존성 추가

feat: 홈화면 테스트 작성

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModelTest.kt
android/app/src/test/java/com/zzang/chongdae/repository/FakeOfferingRepository.kt
android/app/src/test/java/com/zzang/chongdae/util/TestFixture.kt

close #249
Viewmodel Test: 공모글 작성 이미지 테스트 코드

test: 공모글 작성 이미지 테스트 코드 작성

---

android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnUpsideClickListener.kt
android/app/src/main/res/drawable/btn_upside.xml
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/layout/item_offering.xml
android/app/src/main/res/values/style.xml

close #232 
홈화면 레이아웃 수정
마감임박 텍스트 수정
스크롤 수정
https://github.com/user-attachments/assets/10d8248e-6b4e-43be-8f4d-f5c2828d60a1

refactor: 홈화면 수정

---

backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java

close #277 
- pageSize validation 추가

feat: pageSize validation 추가

---

android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/OfferingDetailResponse.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/OfferingCondition.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/OfferingDetail.kt
android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModelTest.kt

close #278 
총대 여부 확인 로직 수정
productUrl -> productUrl?
마감 임박 상태 시 버튼 수정
공모 작성 -> 홈화면 돌아 올 때 새로고침 하도록 수정

fix: 공모 상세 화면 오류 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/layout/fragment_offering_write.xml
android/app/src/main/res/values-v29/themes.xml
android/app/src/main/res/values/style.xml
android/app/src/main/res/values/themes.xml

close #299
가로모드는 모두 잘 작동하는 것 확인했고 
(댓글방 상세에서는 가로일시 스크롤 안되는데 어차피 댓글쓸 때 가로모드를 지원할 필요없다는 판단 아래)
다크 모드에서 몇 개의 뷰 안보이는 것만 수정했습니다.
https://github.com/user-attachments/assets/1c6ddf1f-95d1-4d53-a65a-db6c52e0b5e0

feat: 가로모드, 다크모드 설정

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/OfferingApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/request/ParticipationRequest.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/OfferingDetailDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingDetailRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/OfferingDetailDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingDetailRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/test/java/com/zzang/chongdae/repository/FakeOfferingDetailRepository.kt

close #306 
api변경에 따른 리팩토링
엄습니당

refactor: api변경에 따른 리팩토링

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #288
**글방 새로운 기능 GA Event 설정**
- 댓글방 참여자 확인 Event
- 댓글방 상태 변경 취소 Event
- 댓글방 상태 변경 확정 Event

feat: 댓글방 새로운 기능 GA 연결

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/mypage/MyPageFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/dimens.xml

feat: 마이페이지 사용하는 기능만 보이도록 view 수정

---

backend/http/auth.http
backend/src/main/java/com/zzang/chongdae/auth/controller/AuthController.java
backend/src/main/java/com/zzang/chongdae/auth/controller/CookieProducer.java
backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
backend/src/main/java/com/zzang/chongdae/auth/service/JwtTokenProvider.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/AuthInfoDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/AuthMemberDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/AuthTokenDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/LoginResponse.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupResponse.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/SignupResponseDto.java
backend/src/main/java/com/zzang/chongdae/auth/service/dto/TokenDto.java
backend/src/test/java/com/zzang/chongdae/auth/integration/AuthIntegrationTest.java

close #321 
- 로그인 API 응답에 memberId와 nickname 필드 추가

feat: 로그인 API 응답에 memberId와 nickname 필드 추가

---

backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/ImminentOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/resources/data.sql

close #331 
- 마감임박 필터 정상동작하도록 수정

fix: 마감임박 필터 정상동작하도록 수정

---

backend/src/main/java/com/zzang/chongdae/logging/config/LoggingFilter.java

close #338 
- 커스텀 필터로 인한 h2 console 접속 오류 해결

fix: 커스텀 필터로 인한 h2 console 접속 오류 해결

---

android/app/src/main/java/com/zzang/chongdae/data/local/source/MemberDataStore.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/mypage/MyPageFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/style.xml

close #336 
마이페이지 로직을 구현했습니다. 
- url 연결 로직을 구현
- 로그아웃 기능 구현 (로그인 화면 이동 및 저장된 데이터 삭제)
https://github.com/user-attachments/assets/77b8dfb6-4d0e-4be0-8896-0866518d342d
회원 탈퇴는 일단 form 으로 연결해놓고 @알송 파트니까 넘기겠습니다~ 
+) 로그아웃도 서버상으로 해도 상관 없서용~

feat: 마이페이지 기능 구현 

---

backend/src/main/java/com/zzang/chongdae/offering/config/OfferingConfig.java
backend/src/main/java/com/zzang/chongdae/offering/service/CombinationProductImageExtractor.java
backend/src/main/java/com/zzang/chongdae/offering/service/NaverApiProductImageExtractor.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/OgTagProductImageExtractor.java
backend/src/main/java/com/zzang/chongdae/offering/service/ProductImageExtractor.java
backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/crawler/HtmlCrawler.java
backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/crawler/JsoupHtmlCrawler.java
backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/naver/NaverScrapClient.java
backend/src/test/java/com/zzang/chongdae/offering/config/TestCrawlerConfig.java
backend/src/test/java/com/zzang/chongdae/offering/util/httpclient/crawler/FakeHtmlCrawler.java
backend/src/test/java/com/zzang/chongdae/offering/util/httpclient/crawler/JsoupHtmlCrawlerTest.java

close #347 
- 이미지 url 추출기능으로 naver api 방식을 추가했습니다.
- 기존 크롤링 방식을 우선적으로 시도하고, imageUrl이 빈 값이 나올 경우 naver api를 활용하여 얻는 방식으로 개선했습니다~
기능 자체는 변경하지 않아 refactor로 남기려고 합니다

refactor: og 태그 추출 기능 수정

---

backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
backend/src/test/java/com/zzang/chongdae/offering/domain/OfferingPriceTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #357 
- 할인율 계산 로직을 소수점 둘째자리~~까지~~에서 반올림 했습니다

refactor: 할인율 계산 로직 수정

---

backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #360 
- 총 모집 인원 수 최댓값을 제한합니다.

feat: 총 모집 인원 수 최댓값 설정

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnFilterClickListener.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/style.xml

close #355 
- 필터 오류 수정
- '참여가능만'필터 분기처리 제거
이제 참여가능만 api추가될거라 미리 분기 제거했습니다.
https://github.com/user-attachments/assets/19d8a32b-f978-4898-9e3d-2bf64a58a5fa

fix: 필터 오류 수정

---

backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingCondition.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingStatus.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingAllResponseItem.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/main/java/com/zzang/chongdae/scheduler/config/SchedulerConfig.java
backend/src/main/java/com/zzang/chongdae/scheduler/service/SchedulerService.java
backend/src/test/java/com/zzang/chongdae/global/service/ServiceTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #354 
- 서버 타임존은 인스턴스에 직접 설정하였음.

feat: 자동 확정 기능을 위해 스케줄러 적용

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnUpsideClickListener.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteOptionalFragment.kt
android/app/src/main/res/layout/fragment_home.xml

close #366 
공모 작성 후 홈화면 돌아올 때 새로 작성한 글이 보이지 않는 오류 수정했슴다
https://github.com/user-attachments/assets/b2d02d30-3110-439f-ac7f-90f4de551ed0

fix: 공모 작성 후 홈화면 돌아올 때 새로 작성한 글이 보이지 않는 오류 수정

---

backend/src/main/java/com/zzang/chongdae/auth/config/AuthWebMvcConfig.java
backend/src/main/java/com/zzang/chongdae/auth/config/AuthorizationInterceptor.java
backend/src/main/java/com/zzang/chongdae/auth/service/JwtTokenProvider.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #370 
- API 별 권한 확인 로직 추가
- 인증 필터 적용

feat: API 별 권한 확인 로직 추가

---

backend/src/main/resources/data.sql

refactor: 더미 데이터 칼럼 위치 변경

---

android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/offering/RemoteOffering.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt
android/app/src/main/res/layout/item_offering.xml

close #368 
홈화면 api필드 추가에 따른 대응
리팩토링 후 테스트 중 오류발생해서  테스트할 수 없어서 오류 고친 것도 이슈 별도로 안파고 같이 올렸어용..

refactor: 홈화면 api필드 추가에 따른 대응

---

backend/src/main/java/com/zzang/chongdae/auth/config/AuthWebMvcConfig.java

close #383 
- handlerInterceptor에 swagger-ui URL 추가

fix: API 문서에 접근할 수 없는 현상 해결

---

backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

feat: 공모 단건 조회 API 구현

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/OfferingApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/OfferingRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/offering/OfferingRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/OfferingDetail.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/home/OfferingViewModelTest.kt
android/app/src/test/java/com/zzang/chongdae/repository/FakeOfferingRepository.kt

close #385 
상태 변경  방식을 변경하였습니다!
[기존]
상태가 바뀐 것이 있으면 해당 id값을 가져옴-> id값에 대한 OfferingDetail을 들고옴 -> Offering으로 바꿈
[현재]
상태가 바뀐 것이 있으면 해당 id값을 가져옴-> id값에 대한 Offering들고옴
없슴다

refactor: 상태변경 리팩토링

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/comment/CommentRoomsFragment.kt

close #396 
댓글 입력 후 뒤로가기 시 최근 댓글이 반영되도록 수정
코드 한줄 추가했슴다

fix: 댓글 입력 후 뒤로가기 시 최근 댓글이 반영되도록 수정

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/ParticipationApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/ParticipantRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/ParticipantRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/ParticipantRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/ParticipantRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt

close #365 
공동구매 나가기 기능 구현
https://github.com/user-attachments/assets/f9d3791f-dec7-4cac-971e-3f173f8f4330
나중에 나갈떄 dialog 띄워주면 좋을 것 같아요.
그리고 현재 총대는 나가지 못하는데, 토스트 메시지 띄우기는 에러핸들링 하면서 할게요~

feat: 댓글방 공동구매 나가기 API 연결

---

backend/src/main/java/com/zzang/chongdae/auth/config/AuthWebMvcConfig.java

close #405 
- handlerInterceptor 예외 추가

fix: /auth/refresh endpoint accessToken 검증 예외 추가

---

android/app/build.gradle.kts
android/app/proguard-rules.pro

close #412 
proguard를 사용한 난독화 적용

feat: proguard를 사용한 난독화 적용

---

backend/src/main/java/com/zzang/chongdae/auth/controller/CookieConsumer.java
backend/src/main/java/com/zzang/chongdae/auth/exception/AuthErrorCode.java

close #408 
- refreshToken 만료 시 403 반환하도록 수정

feat: refreshToken 만료 시 403 반환하도록 수정

---

backend/src/main/resources/data.sql

fix: 테스트 깨지는 문제 해결

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/AuthApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/request/AccessTokenRequest.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/AuthRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/AuthRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/AuthRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/AuthRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/login/LoginActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/login/LoginViewModel.kt
android/app/src/test/java/com/zzang/chongdae/repository/FakeAuthRepository.kt

close #398 
email을 보내던 방식에서 카카오 accessToken을 보내는 방식으로 변경했습니다.

feat: 로그인 api 변경 반영

---

backend/src/main/resources/application.yml

close #429 
Spring Timezone을 KST로 설정 완료

feat: Spring Timezone KST로 설정

---

Dockerfile

close #431
- 컨테이너 생성 시 timezone 환경변수를 추가했습니다~

fix: 컨테이너 타임존 변경

---

backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/OfferingFetchStrategy.java

close #433 
- Offering 목록 조회 시 NPE 해결

fix: Offering 목록 조회 시 NPE 해결

---

android/app/src/main/java/com/zzang/chongdae/data/repository/AuthRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/domain/util/DataError.kt

refactor: refresh시 401이 오는 경우에 대한 에러핸들링 추가

---

android/app/build.gradle.kts

chore: 버전 업데이트

---

backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java

close #444 
- 외래키 필드 notnull 조건 추가

refactor: 외래키 필드 notnull 조건 추가

---

.github/workflows/backend-dev-ci-cd.yml

close #446 
- prod 불필요한 트리거 주석 처리

chore: prod 불필요한 트리거 주석 처리

---

backend/src/main/java/com/zzang/chongdae/offering/service/OgTagProductImageExtractor.java

close #450 
og 크롤링 정상 작동 시 http https 프로토콜 정보 제거

hotfix: og 크롤링 정상 작동 시 http https 프로토콜 정보 제거

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #462 
채팅방 입력 UIUX 개선: 전송 버튼을 눌렀는데 키보드가 내려가는 현상 수정

feat: 채팅방 입력 UIUX 개선

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt

feat: 이미지 로딩 기능 복원

---

android/app/build.gradle.kts
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/style.xml

close #392 
필터 텍스트 크기 키우기
검색한 공모가 없을 시 명시적으로 알려주기.
화면을 아래로 당기면 리스트가 새로고침 되도록 구현
검색이 어떤 기준으로 진행되는지 placeholder로 명시하기
검색창에 x버튼 만들기(클릭 시 검색 텍스트 지워짐 + 전체 공모 보여지는 초기화면보여주도록)
SwipeRefreshLayout 의존성 추가했습니다.
```kotlin
// swipe refresh layout
implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")
```

refactor: 홈 화면 UX개선

---

android/app/src/main/res/layout/activity_comment_detail.xml
android/app/src/main/res/layout/item_my_comment.xml

close #467 
채팅 UX 개선: 채팅 전송 버튼 사이즈 변경 및 나의 채팅 사이즈 변경

refactor: 채팅 UX 개선

---

backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java

close #482 
- OfferingEntity Soft Delete 적용

feat: OfferingEntity Soft Delete 적용

---

backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
backend/src/main/java/com/zzang/chongdae/offering/exception/OfferingErrorCode.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #470 
- 거래 날짜 검증 로직 추가
- 테스트 코드 추가

feat: 거래 날짜 검증 로직 추가

---

backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #486 
- 공모 목록 조회 시 soft delete 결과 적용되었는지 확인하는 테스트 추가

test: 공모 목록 조회 시 soft delete 결과 적용되었는지 확인하는 테스트 추가

---

backend/build.gradle
backend/src/main/java/com/zzang/chongdae/auth/config/AuthWebMvcConfig.java
backend/src/main/resources/application.yml

close #492 
- Spring Actuator로 health check api 생성했습니다
- 인프라에 대한 설정이 애플리케이션에 침투하는 걸 막기 위해 api를 새로 만들기보단, Spring Actuator가 제공하는 기능을 사용했습니다.

feat: Spring Actuator로 health check api 생성

---

.github/workflows/backend-prod-ci-cd.yml

chore: prod-a, prod-b에 어플리케이션을 배포하도록 변경

---

android/app/build.gradle.kts

chore: 안드로이드 버전 v1.1.2로 변경

---

backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java

close #504 
- Member, Offering, OfferingMember, Comment 더미데이터 추가
- Offering 테이블 인덱스 설정 및 쿼리 최적화
위 빨간 라인은 IntelliJ가 인식하지 못하는 문법으로 보입니다. 쿼리는 정상 동작 합니다!

refactor: OfferingRepository 쿼리 최적화

---

backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java

close #520 
- osiv 끄면서 깨지는 테스트 수정

test: osiv 끄면서 깨지는 테스트 수정

---

backend/src/test/java/com/zzang/chongdae/member/service/NicknameGeneratorTest.java

close #523 
- 닉네임 생성 파일 변경 후 테스트 수정

test: 닉네임 생성 파일 변경 후 테스트 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zzang/chongdae/presentation/view/MainActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt

close #538
총대마켓 웹에서 참여하기를 누르면 우리 공모글 detail 페이지로 넘어가는 기능 구현
만약, 앱이 안깔려있을시 총대마켓 app store로 이동
- manifest 파일 수정
-  MainActivity에서 OfferingDetail로 연결
-  Play Console 딥링크 설정
현재 로그인 로직상의 이유로 로그인이 안되어 있는 사용자의 경우에는 로그인하고 offering detail이 아닌 MainActivity로 넘어가는 사소한 문제가 존재하는데, 코드를 더럽혀서 이걸 구현할지 말지 고민중입니다.
https://github.com/user-attachments/assets/bf576d2d-3f20-4e29-a38f-33c82940d61d

feat: playstore Deeplink 연결 

---

.github/workflows/android.yml
android/app/build.gradle.kts

feat: 릴리즈 버전 업데이트

---

backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java

close #557 
- Native Query 미반영 서비스 코드 수정

fix: Native Query 미반영 서비스 코드 수정

---

backend/src/main/resources/templates/detail.html
backend/src/main/resources/templates/index.html

close #543 
아래와 같은 이미지 깨짐 현상을 해결했습니다~~

fix: 웹 페이지에서 공모 데이터에 선택 필드 값이 존재하지 않을 때 예외 처리

---

backend/src/main/resources/templates/detail.html

close #560 
- 웹 뷰 상세조회 시 null값 처리 안된 부분 해결

feat: 웹 뷰 상세조회 시 null값 처리 안된 부분 해결

---

.github/workflows/backend-dev-ci-cd.yml
.github/workflows/backend-prod-ci-cd.yml

close #566 
- chore: CI/CD 스크립트 트리거 브랜치 수정

chore: CI/CD 스크립트 트리거 브랜치 수정

---

backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/scheduler/service/SchedulerService.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #584 
**Approve 전 PR 브랜치 설정 확인해주시기 바랍니다!!**
- SchedulerService의 Confirm 시점 변경
- OfferingService의 공모 마감 날짜 설정 검증 기능 수정
- e.g.) 2024년 10월 15일에 공모 마감일로 설정 시, 2024년 10월 16일 00시 00분 00초에 스케줄러 작동

refactor: 스케줄링 시점 수정

---

backend/src/main/java/com/zzang/chongdae/offering/domain/UpdatedOffering.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #585 
- MeetingDate 검증 로직의 인자를 LocalDate로 수정하였다.
- Update 기능 실행 시 Status도 다시 계산할 수 있게끔 수정하였다.
- 추가로 이전 PR에서 놓쳤던 수정 사항을 보완하였다.

refactor: Update 시 상태를 변경할 수 있도록 수정

---

backend/src/test/java/com/zzang/chongdae/comment/service/CommentServiceTest.java

test: 실패하는 테스트 수정

---

android/app/src/main/res/layout/fragment_offering_detail.xml

close #617 
참여하지 않은 공모에 대해서 버튼이 나오지 않는 버그 수정

fix: 참여하지 않은 공모에 대해서 버튼이 나오지 않는 버그 수정

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/res/layout/activity_comment_detail.xml

close #620
- connection error 핸들링 방식 수정

feat: connection error 핸들링 방식 수정

---

.github/workflows/backend-dev-ci-cd.yml

close #634 
- backend dev cicd trigger 변경

chore: Dev CI/CD 트리거 수정

---

backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/storage/config/StorageConfig.java
backend/src/main/java/com/zzang/chongdae/storage/exception/StorageErrorCode.java
backend/src/main/java/com/zzang/chongdae/storage/service/AmazonS3StorageService.java
backend/src/main/java/com/zzang/chongdae/storage/service/LocalStorageService.java
backend/src/main/java/com/zzang/chongdae/storage/service/StorageService.java
backend/src/main/resources/application.yml
backend/src/test/java/com/zzang/chongdae/global/config/TestConfig.java
backend/src/test/java/com/zzang/chongdae/offering/config/TestStorageConfig.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/util/FakeStorageService.java

close #657 
- s3의 의존을 끊으려고 StorageService를 추상화 시켰어요
- 아울러, `LocalStorageService`를 추가해서 서버 로컬에 저장할 수 있도록 기능을 추가했어요!

feat: s3에 의존적이지 않도록 이미지 업로드 추상화

---

android/app/src/androidTest/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivityTest.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModelTest.kt

close #688
comment detail test 추가 (Unit test, Ui test)
usecase 적용 전에 test를 더 작성해보았습니다~
mock 사용해서 ui test를 더 자세하게 구현하고 싶었는데 시간이 부족하더라구용 담에 보완할게요!! 
test외엔 isPollingActive Live data 를 활용해서 polling 상태를 외부에서 확인할 수 있도록 변경한 코드밖에 없습니다!!

test: comment detail test 추가

---

README.md

docs: 총대마켓 대표 이미지 변경

---

android/app/src/main/java/com/zzang/chongdae/data/remote/dto/request/ParticipationRequest.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingDetailRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingDetailRepository.kt
android/app/src/main/java/com/zzang/chongdae/domain/usecase/offeringdetail/SaveParticipationUseCase.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/bottomsheet/OfferingDetailBottomSheetDialog.kt
android/app/src/main/res/drawable/bg_bottom_sheet_dialog.xml
android/app/src/main/res/drawable/bg_gray300_radius_5dp.xml
android/app/src/main/res/drawable/bg_main_color_radius_10dp.xml
android/app/src/main/res/drawable/bg_main_color_radius_18dp.xml
android/app/src/main/res/layout/dialog_offering_detail_bottom_sheet.xml
android/app/src/main/res/layout/fragment_offering_detail.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/style.xml

close #707 
상세화면 상품 구매 갯수 선택 기능을 구현했습니다.
하면서, 홈화면에서 스와이프로 새로고침 시 업데이트가 되지 않는 경우가 있어서 이부분도 해결했어요!
https://github.com/user-attachments/assets/e62044ed-7229-4bac-86d2-d029b4bb67a9

feat: 상세화면 상품 구매 갯수 선택 기능 추가

---

backend/src/test/java/com/zzang/chongdae/global/helper/ConcurrencyExecutor.java
backend/src/test/java/com/zzang/chongdae/member/integration/MemberIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceConcurrencyTest.java

close #719 
submit 메서드로 동시 요청한 후 CountDownLatch로 모두 호출될 때까지 기다리기
invokeAll 메서드로 동시 요청한 후 모두 호출될 때까지 기다리기

test: 동시 요청 테스트 메서드 리팩터링
