backend/http/http-client.env.json
backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/comment/repository/Comment.java
backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/common/repository/entity/BaseTimeEntity.java
backend/src/main/java/com/zzang/chongdae/member/repository/entity/MemberEntity.java
backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingCondition.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingStatus.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingDetailResponse.java
backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMemberRole.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRepository.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRole.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java
backend/src/main/resources/application.yml
backend/src/main/resources/data.sql

close #17 
- 공동구매 상세 조회 API 구현
- 기존 코드 리팩토링

feat: 공동구매 상세 조회 기능 구현

---

.github/workflows/backend-ci-cd.yml
Dockerfile

close #29 
- chore: actions 적용 브랜치 설정

chore: actions 적용 브랜치 설정

---

backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java

close #81 
- 댓글 목록 조회 시 시간순으로 정렬되지 않는 쿼리를 수정

fix: 시간순 정렬 쿼리 추가

---

android/app/build.gradle.kts
android/app/src/main/java/com/zzang/chongdae/data/repository/remote/OfferingsRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/domain/paging/OfferingPagingSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingsRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt

close #76 
paging3 활용하여 홈 화면 무한 스크롤 기능 구현하였습니다.
https://github.com/user-attachments/assets/71bac813-280c-4508-9c3b-1905321b2bea

feat: 홈 화면 무한 스크롤 기능 구현

---

.github/workflows/backend-ci-cd.yml
backend/build.gradle

close #110 
-  jar 태스크 비활성화하고 bootJar 태스크로만 JAR 파일 생성
- 🍀해결 완!🍀 `./gradlew clean build` 명령어 하나만으로도 API docs 배포 환경에서 정상적으로 뜨는 거 확인했습니다:)
[원인]
- jar task와 bootJar task 둘다 JAR 파일을 생성하는 task인데, 원래 build 과정에서 둘다 실행해서 문제였습니다.
- 아마 기존엔 앞에 jar task 로 만든 JAR 파일을 캐싱해 사용한 거 같습니다.
[해결]
- jar task를 비활성화했습니다.
[정보]
- jar task: 라이브러리를 생성하거나, 종속성을 직접 관리하는 경우에 유용
- bootJar task: Spring Boot 애플리케이션을 배포하고 실행 가능한 형태로 패키징하는데 사용

chore: CI 빌드 스크립트 중 중복되는 task 제거해 성능 개선

---

backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/comment/service/dto/CommentAllResponseItem.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java

close #149 
- 댓글방 메시지 조회 시 commentId 필드 추가

feat: 댓글방 메시지 조회 시 commentId 필드 추가

---

backend/src/main/java/com/zzang/chongdae/comment/controller/CommentController.java
backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/offering/config/OfferingConfig.java
backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
backend/src/main/java/com/zzang/chongdae/offering/util/httpclient/JsoupHtmlCrawler.java
backend/src/main/java/com/zzang/chongdae/offeringmember/controller/OfferingMemberController.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/global/integration/IntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java

close #151
- 테스트 request 형태를 Map에서 DTO로 변경
- 문서화 description 내 optional 정보 추가
- 예외 처리에 대한 문서화
- 가독성 향상을 위해 `내부클래스명 + requestDescriptors`, `내부클래스명 + successSnippets` 등과 같이 사용하던 변수명을 `requestDescriptors`, `successSnippets` 등으로 통일.

refactor: 제품 코드와 API 문서 동기화

---

android/app/build.gradle.kts
android/app/src/main/assets/html/address.html
android/app/src/main/java/com/zzang/chongdae/presentation/view/address/AddressFinderDialog.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/address/AddressWebViewClient.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/address/JavascriptInterface.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/address/OnAddressClickListener.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnOfferingClickListener.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingViewHolder.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OnParticipationClickListener.kt
android/app/src/main/res/layout/dialog_address_finder.xml
android/app/src/main/res/layout/item_offering.xml

close #159 
주소검색 api를 활용해 주소검색 다이얼로그를 구현하였습니다.
[사용법]
dataBinding같은 부분들을 제외하고 러프하게 작성한 사용 코드 예시입니다.
아래와 같이 클릭 리스너와 결과 데이터를 읽는 리스너 두가지만 설정해주시면 됩니다.
아마 사용 시 수정할 부분은 `etAddress` 대신에 직접 구현하신 주소검색창의 id로 변경 정도 일 것 같아요.
```
// 주소검색 다이얼로그가 뜨도록 리스너 달아줌
binding.etAddress.setOnClickListener { 
AddressFinderDialog().show(parentFragmentManager, this.tag)
}
// 주소를 클릭했을 때 해당 데이터를 읽는 리스너 설정
setFragmentResultListener(AddressFinderDialog.ADDRESS_KEY) { _, bundle ->
binding.etAddress.text = bundle.getString(AddressFinderDialog.BUNDLE_ADDRESS_KEY)
}
```
https://github.com/user-attachments/assets/9388d2de-ce75-4a14-af82-603e4ad855ed

feat: 주소검색 기능구현

---

backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingPrice.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #244 
- 원 가격이 없는 경우 n빵 가격을 비교하지 않도록 변경

fix: 원 가격이 없는 경우 n빵 가격을 비교하지 않도록 변경

---

backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java

close #265 
- 마감 임박 공모 조회 시 수동 마감 된 공고가 보이지 않도록 조치합니다

fix: 마감 임박 공모 조회 시 수동 마감 된 공고가 보이지 않도록 변경

---

.github/workflows/backend-ci-cd.yml
Dockerfile
backend/src/main/java/com/zzang/chongdae/logging/config/LoggingFilter.java
backend/src/main/java/com/zzang/chongdae/logging/config/LoggingInterceptor.java
backend/src/main/resources/application.yml

chore: logback 설정 진행

---

backend/src/main/java/com/zzang/chongdae/logging/config/LoggingFilter.java
backend/src/main/java/com/zzang/chongdae/logging/config/LoggingInterceptor.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #272 
- 이미지 업로드 API의 responseBody가 두 번 뜨는 오류 해결
- 추후에, 이미지 업로드에서 뜨는 에러 로깅 별도로 필요함

fix: 이미지 업로드 API의 responseBody가 두 번 뜨는 오류 해결

---

android/app/build.gradle.kts

chore: change version name

---

.github/workflows/android.yml
android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/build.gradle.kts

close #295 
카카오 계정 로그인 기능을 구현하기 위해 매니페스트에서 로컬프로퍼티를 가져오면 ci가 터졌는데 이유를 알아냈어용.. yml파일에서 "/" 하나를 빼먹어서 였습니다.. 엉엉 ㅠㅠ

feat: 카카오 계정 로그인 기능 구현 시 CI가 실패하는 문제 해결

---

backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantCountResponseItem.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantPriceResponseItem.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantResponse.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ProposerResponseItem.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java

close #326 
- ParticipantResponse에 참여 인원 현황, 예상 정산 가격 추가
기존 OfferingMemberService의 getAllParticipant에서 내가 참여하고 있는 공모인지 검증하기 위해, Offering 엔티티를 찾아오는 과정이 있습니다. 여기서 Offering에 대한 정보가 메서드 내에 존재하기에, 하기 댓글방 슬라이딩 뷰와 같이 보여지도록 현재원, 총원, 예상 정산 가격을 Offering을 활용하여 추가하였습니다. 큰 변경 없이 Response에 슬라이딩 뷰에 대한 정보를 한 API로 전달할 수 있었습니다.
여기서 고민이 발생했습니다. 현재 이 공모에 대한 참여자가 누군지에 대한 정보를 받는 것을 요청하는 API에서, OfferingMember가 아닌 Offering의 내용이 직접적으로 들어가도 되는가? 그렇다면 다른 API로 분리해야 하는 것이 아닌가? 라는 것입니다.
아직 현 코드에 대한 리팩토링은 진행하지 않았습니다. 위와 같은 점에 대해서 논의를 더 해봐야 도메인 로직으로 분리하기 적절하다고 판단했습니다. 특히 Proposer, Participants로 분리해볼만한 여지가 여실하네요.
가감없는 피드백 부탁합니다.

feat: ParticipantResponse에 참여 인원 현황, 예상 정산 가격 추가

---

android/app/src/main/java/com/zzang/chongdae/data/remote/api/AuthApiService.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/source/AuthRemoteDataSourceImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/repository/AuthRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/data/source/AuthRemoteDataSource.kt
android/app/src/main/java/com/zzang/chongdae/domain/repository/AuthRepository.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/login/LoginViewModel.kt
android/app/src/test/java/com/zzang/chongdae/repository/FakeAuthRepository.kt

close #345 
- 로그인 시에도 회원가입 시와 마찬가지로 서버에서 memberId와 nickName을 내려받습니다. 그리고 데이터스토어에 저장해줍니다.
별거 없서용~

feat: 로그인 시에도 memberId와 nickName을 받아서 data store에 저장하는 기능 구현

---

backend/src/main/java/com/zzang/chongdae/offering/domain/OfferingFilter.java
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/HighDiscountOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/ImminentOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/domain/offeringfetchstrategy/JoinableOfferingStrategy.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingFetcher.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingAllResponseItem.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #353 
- 공모글 목록 조회 필터링 수정 및 추가

refactor: 공모글 목록 조회 필터링 수정 및 추가

---

android/app/src/main/res/layout/fragment_comment_rooms.xml

close #374 
댓글방 목록의 마지막 댓글방이 안보이는 문제 해결했습니다
수정전
수정후
그리고 기존에는 각각의 아이템에만 하단에 구분선이 붙어있었기 때문에 리사이클러뷰를 아래로 땡기면 이 구분선이 사라져버렸는데 리사이클러뷰의 layout 최하단에도 구분선을 하나 붙여서 사라지지 않게 했습니다.
별거없음

fix: 댓글방 목록의 마지막 댓글방이 보이지 않는 문제 수정

---

android/app/src/main/java/com/zzang/chongdae/data/mapper/OfferingMapper.kt
android/app/src/main/java/com/zzang/chongdae/data/remote/dto/response/offering/RemoteOffering.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/Offering.kt
android/app/src/main/java/com/zzang/chongdae/domain/model/OfferingDetail.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/write/OfferingWriteViewModel.kt
android/app/src/main/res/layout/item_offering.xml
android/app/src/test/java/com/zzang/chongdae/repository/FakeOfferingRepository.kt
android/app/src/test/java/com/zzang/chongdae/util/TestFixture.kt

close #378 
주소에서 동을 파싱해서 서버로 보내줍니다. 이제 공모 목록에서 동을 보여줍니다.
만약 동이 없는 주소일 경우 blank로 아무것도 안 띄웁니다.

feat: 공모글 목록에서 주소의 동을 보여주는 기능 구현

---

.github/workflows/backend-ci-cd.yml
backend/build.gradle

close #143 
- JAR 파일에 OAS 파일 누락되는 이슈 해결 및 중복 task 제거
- 해당 코드 적용 후, 로컬 환경에서 OAS 파일을 삭제한 후 빌드했을 때, JAR 파일에 OAS 파일이 정상적으로 포함되는 것을 확인했습니다.
- [문제] 해당 코드 적용 전에는 OAS 파일을 삭제한 후 빌드했을 때, JAR 파일에 OAS 파일이 포함되지 않았습니다.
- static 경로의 파일들은 모두 processResources 태스크에서 처리되는데, 이 태스크는 OAS 파일을 생성하는 태스크보다 앞서 실행됩니다.
- 따라서 이후 실행되는 bootJar 태스크는 processResources 태스크에서 처리한 static 경로의 파일만 인식하기 때문에, OAS 파일을 인식하지 못했습니다.
- [해결] 이 문제를 해결하기 위해 bootJar 태스크에서 OAS 파일을 명시적으로 포함시켰습니다. 이렇게 하면 bootJar 태스크가 OAS 파일을 인식하여 JAR 파일에 포함할 수 있게 됩니다.
- 해당 코드 적용 후, 배포 환경에서도 동일하게 oas 파일 누락되지 않는 거 확인했습니다.

chore: JAR 파일에 OAS 파일 누락되는 이슈 해결 및 중복 task 제거

---

backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantCountResponseItem.java

close #399 
- 참여자 목록 조회 API에서 totalCount 반환하지 않는 이슈 해결

fix: 참여자 목록 조회 API에서 totalCount 반환하지 않는 이슈 해결

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OnProductLinkClickListener.kt
android/app/src/main/res/layout/fragment_offering_detail.xml

close #395 
- 바로가기 안눌림 오류
- 바로가기에 하이퍼링크를 직접 거는 방식 대신 클릭 이벤트를 설정하는 방식으로 리팩토링하여 해결하였습니다.
- 공구 상세페이지에서 주소가 길 경우 말줄임표 또는 줄바꿈을 통해 보여주도록 수정
- 주소, 상세주소 모두 최대 2줄까지 보여주고 넘어갈 시 끝에 말 줄임...으로 표시하도록 리팩토링 하였습니다.
없습니다!

fix: 공구 상세 페이지 오류 해결

---

android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
android/app/src/test/java/com/zzang/chongdae/presentation/view/home/OfferingViewModelTest.kt

close #437 
리프레시 토큰 만료 시 데이터스토어를 비우고 로그인 화면으로 이동하는 기능 구현

feat: 리프레시 토큰 만료 시 데이터스토어를 비우고 로그인 화면으로 이동하는 기능 구현

---

android/app/src/main/java/com/zzang/chongdae/data/repository/ParticipantRepositoryImpl.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt

feat: 댓글방 에러핸들링

---

android/app/src/main/res/layout/item_offering.xml

close #451 
공모 제목 최대 1문장, 넘어갈 시 말줄임 하도록 구현

fix: 공모 제목 및 가격 줄바꿈, 말줄임 되도록 수정

---

backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingController.java
backend/src/main/java/com/zzang/chongdae/offering/domain/CommentRoomStatus.java
backend/src/main/java/com/zzang/chongdae/offering/exception/OfferingErrorCode.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #488 
- 공모 삭제 API 구현
- 총대만 삭제 가능
- 거래 진행 중 (확정 후 ~ 완료 전) 삭제 불가능

feat: 공모 삭제 API 구현

---

backend/src/main/java/com/zzang/chongdae/auth/config/AuthWebMvcConfig.java
backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingReadOnlyController.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

close #507 
- 총대마켓 앱을 홍보하기 위해 웹에서 사용할 API를 추가했습니다.
- ⚠️ **해당 API는 쿠키 없이 접근 가능합니다.**
- 기존에 제공하는 API의 접근 권한을 수정하는 것 보다 `/read-only`로 시작하는 API end-point를 만들어서 관리하는 것이 편하다고 생각하여 이 구조를 사용하게 되었습니다.
혹시 이 설계에 의견 있으면 가감 없이 많은 의견 제시 부탁드립니다 (제발~~)

feat: 총대마켓 접근권한 수정

---

backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #548 
- 삭제한 Offering도 검증에 사용할 수 있도록 findById를 findByIdWithDeleted로 교체하고, 필요한 부분에 교체하였다.
- Native Query로 `is_deleted = false`가 붙지 않도록 구현하였다.
- 더불어 테스트 코드에 날짜가 하드 코딩되어 fail하는 테스트에 대해, 항상 실행 일시 기준 내일의 값을 넣을 수 있도록 수정하였다.
실패하지 않는 커밋을 만들기 위해 테스트 코드 수정도 추가했습니다.

feat: Offering 쿼리에 Native Query 적용(+ 테스트 코드 수정)

---

.github/workflows/android.yml

close #568 
develop 브랜치에서 CI CD가 돌도록 수정

chore: develop 브랜치에서 CI CD가 돌도록 수정

---

backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/test/java/com/zzang/chongdae/global/service/ServiceTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java

close #579 
- 현재 시간 계산 로직에 누락된 clock 추가

fix: 현재 시간 계산 로직에 누락된 clock 추가

---

backend/src/main/resources/templates/index.html

close #590 
- web에서 인원 만석, 모집 마감 상태가 제대로 반영되지 않은 문제가 있었어요~
- 없는 상태값인 CLOSED를 비교해서 스타일이 제대로 적용되지 않았어요
- OfferingStatus 값을 확인하고 CLOSED를 CONFIRMED로 변경해서 해결했습니다~

fix: 모집 마감 상태 스타일 미적용 해결

---

android/app/build.gradle.kts
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt
android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
android/app/src/main/res/layout/fragment_offering_detail.xml
android/app/src/main/res/layout/fragment_offering_detail_shimmer.xml
android/gradle/libs.versions.toml

close #544 
- 로딩 상태를 추가하여 로딩이 완료 된 경우 공모 상세 페이지를 보여주도록 하였습니다.
- facebook의 skeleton ui라이브러리를 사용하였습니다.
- 의존성 추가해주었습니다.
```kotlin
// Skeleton-UI
implementation(libs.shimmer)
```
https://github.com/user-attachments/assets/80d93097-ae50-426a-93cd-443e46951b75
[deleay 3초]
https://github.com/user-attachments/assets/a2cca046-ac25-476d-83fd-6fa8e09b64bf
[delay X]
https://github.com/user-attachments/assets/9c53356b-eb71-4149-a30f-7cfb12f5e701

refactor: 공모 상세 페이지 진입 시 로딩이 된 후에 화면을 보여주도록 수정

---

backend/src/main/java/com/zzang/chongdae/offering/domain/UpdatedOffering.java
backend/src/main/java/com/zzang/chongdae/offering/exception/OfferingErrorCode.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java

close #625 
- meetingDate 검증 로직 수정
- 에러 내용 수정

refactor: meetingDate 검증 로직 수정

---

backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSender.java
backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSubscriber.java

fix: FCM null 토큰에 대한 예외 처리

---

.github/workflows/backend-prod-ci-cd.yml

chore: Prod에 무중단 배포 CI/CD 적용

---

.github/workflows/backend-dev-ci-cd.yml

close #646 
- dev와 test 서버에서 사용될 FCM 서버 분리
현재 사용 중인 서버: local, dev, prod + test
현재 local / (dev, test, prod) 총 두 개의 FCM 서버를 사용하는 상태이다.
하지만 test 부하 테스트 도중 prod와 같은 FCM 서버를 사용함을 알게 되었다.
따라서 dev와 test 서버에 대한 FCM 서버를 분리했다.

fix: FCM 서버 dev 환경 분리

---

.github/workflows/backend-dev-ci-cd.yml
backend/http/auth.http
backend/http/offering-member.http
backend/http/offering.http
backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/event/config/AsyncConfig.java
backend/src/main/java/com/zzang/chongdae/event/domain/CancelParticipateEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/DeleteOfferingEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/LoginEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/ParticipateCancelEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/ParticipateEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/SaveCommentEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/SaveOfferingEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/UpdateStatusEvent.java
backend/src/main/java/com/zzang/chongdae/event/exception/AsyncEventExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/event/service/FcmEventListener.java
backend/src/main/java/com/zzang/chongdae/notification/exception/NotificationErrorCode.java
backend/src/main/java/com/zzang/chongdae/notification/exception/NotificationException.java
backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSender.java
backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationSubscriber.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/event/exception/AsyncEventExceptionHandlerTest.java
backend/src/test/java/com/zzang/chongdae/event/service/FcmEventListenerTest.java
backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java

feat: 푸쉬 알림 비동기 처리

---

backend/src/main/java/com/zzang/chongdae/logging/config/LoggingInterceptor.java

close #677 
쿼리스트링이 존재하는 요청에 대해서도 `uri=/offerings`와 같이 쿼리스트링이 표시되지 않아 로그를 확인할 때 매우 불편했음.
쿼리스트링이 존재하는 요청에 대해 `uri=/offerings?filter=RECENT&search=title&last-id=10&page-size=10`와 같이 쿼리스트링이 함께 표시되도록 함.

refactor: 응답 로그가 쿼리스트링 출력하도록 보완

---

backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java
backend/src/test/java/com/zzang/chongdae/global/helper/ConcurrencyExecutor.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceConcurrencyTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceTest.java

close #664
같은 사용자가 같은 공모에 중복 참여 가능한 상황을 해결하기 위함.
동시성 이슈 해결 과정은 [제 블로그](https://helenason.tistory.com/21)에 정리해두었어요. 자세한 내용이 궁금하시면 읽어주시면 됩니다! 조회수 늘리기는 덤 ㅎㅎ
요약해서 이야기하자면, 총 네 가지 방법을 떠올렸고 그 중 두 가지 방법 낙관적 잠금과 비관적 쓰기 잠금을 적용할 수 있었어요. 저는 비관적 쓰기 잠금을 걸기로 결정했습니다.
먼저, 참여하기 API는 동시성 이슈 발생률이 낮은 편이기 때문에 속도 테스트를 해보았을 때 낙관적 잠금과 비관적 잠금의 차이가 없었어요. 그래서 성능 측면은 고려하지 않았고, 불필요하게 쿼리가 발생하는 낙관적 잠금의 단점을 피하기 위해 비관적 쓰기 잠금을 선택하도록 하였습니다! 블로그에는 언급하지 않았지만, 낙관적 잠금을 선택할 경우 적절한 예외 처리에 대한 고민이 길어지기도 했어요.

refactor: 데이터베이스 락을 통해 중복 참여 방지

---

backend/src/main/java/com/zzang/chongdae/event/service/FcmEventListener.java
backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationService.java
backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/event/service/FcmEventListenerTest.java
backend/src/test/java/com/zzang/chongdae/event/service/TestEventPublisher.java
backend/src/test/java/com/zzang/chongdae/global/domain/OfferingFixture.java
backend/src/test/java/com/zzang/chongdae/global/helper/ConcurrencyExecutor.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceConcurrencyTest.java
backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceTest.java

close #674 
[블로그에 정리했습니다.](https://helenason.tistory.com/22) 길지 않은 글이에요.
하지만 `@TransactionalEventListener`에 대해 더 궁금하신 분은 [이 글](https://helenason.tistory.com/23)을 참고해주시면 됩니다.
이전 PR이 아직 머지되지 않아 이번 브랜치는 이전 PR 브랜치 기반으로 진행했는데요. 그렇기 때문에 커밋 기록이 병합되어 있는 상태입니다. 이번 커밋만 보시려면 [여기](https://github.com/woowacourse-teams/2024-chongdae-market/pull/675/files/215bf321f043b657390b3abb2aa661eb4bd80919..bdb614f45b4c715224375a8babd71699ba7fe24c)를 참고해주세요.

refactor: 이벤트 발행 과정에서 예외 발생 시 이벤트 발행되지 않도록 수정

---

backend/src/test/java/com/zzang/chongdae/notification/config/TestNotificationConfig.java
backend/src/test/java/com/zzang/chongdae/notification/service/StubNotificationSender.java
backend/src/test/java/com/zzang/chongdae/notification/service/StubNotificationSubscriber.java

close #685 
테스트 환경에서 FCM 서버 대체하던 클래스명 fake -> stub 변경

test: 테스트 환경에서 FCM 서버 대체하던 클래스명 fake -> stub 변경

---

backend/src/main/java/com/zzang/chongdae/auth/config/AuthClientConfig.java
backend/src/main/java/com/zzang/chongdae/auth/service/AuthClient.java
backend/src/main/java/com/zzang/chongdae/auth/service/AuthService.java
backend/src/main/java/com/zzang/chongdae/auth/service/client/DevAuthClient.java
backend/src/main/java/com/zzang/chongdae/auth/service/client/ProdAuthClient.java
backend/src/test/java/com/zzang/chongdae/auth/config/TestAuthClientConfig.java
backend/src/test/java/com/zzang/chongdae/auth/integration/AuthIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/auth/service/StubAuthClient.java
backend/src/test/java/com/zzang/chongdae/global/config/TestConfig.java
backend/src/test/java/com/zzang/chongdae/member/service/NicknameGeneratorTest.java

close #693 
- 테스트 구동 시 AuthClient 빈주입이 안됬던 현상을 해결합니다.
- 테스트 환경과 프로덕션 환경을 분리하기 위해 Stub객체를 활용하는 선택을 했습니다. 외부 API를 호출하는 실수를 방지하기 위함입니다
테스트환경과 분리하기 위해 코드를 작성하다보니 기존 AuthClient를  인터페이스로 변경했고 TestConfiguration를 별도로 작성했습니다.
솔직히 AuthClientConfiguration에 `test` 프로파일 한 줄로 작성한 것 보다 품이 많이 들어간 것 같은데 여러분들의 의견이 필요합니다.
**요약 : `test` 프로파일 추가 vs 지금 PR처럼 프로덕션과 테스트환경 분리**

fix: 테스트 구동 시 인증 설정 관련 빈 주입 오류 해결

---

backend/src/main/java/com/zzang/chongdae/comment/repository/CommentRepository.java
backend/src/main/java/com/zzang/chongdae/comment/repository/entity/CommentEntity.java
backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
backend/src/main/java/com/zzang/chongdae/event/domain/CancelParticipateEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/ParticipateEvent.java
backend/src/main/java/com/zzang/chongdae/event/domain/SaveCommentEvent.java
backend/src/main/java/com/zzang/chongdae/event/service/FcmEventListener.java
backend/src/main/java/com/zzang/chongdae/notification/service/FcmNotificationService.java
backend/src/main/java/com/zzang/chongdae/notification/service/message/CommentMessageManager.java
backend/src/main/java/com/zzang/chongdae/notification/service/message/ParticipationMessageManager.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/OfferingMemberRepository.java
backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantResponse.java
backend/src/test/java/com/zzang/chongdae/comment/integration/CommentIntegrationTest.java

close #687 
N+1 문제를 해결하기 위해 아래 두가지를 적용하였습니다.
- 로딩 전략 EAGER → LAZY
- 기존 쿼리 → fetch join
자세한 과정은 [블로그](https://helenason.tistory.com/25)를 참고해주세요. N+1 문제가 발생했던 기능은 참여자 목록 조회와 채팅방 목록 조회였고, 두 기능 모두에서 해결 완료하였습니다.
추가로, N+1 문제를 해결하는 과정에서 다른 문제도 발견했습니다. 알림 로직에서 LazyInitializationException이 발생한 문제인데요. 비동기 스레드에서 발생한 예외를 로깅만 하고 따로 처리하지 않고 있기 때문에 이제서야 로그를 통해 발견하게 되었습니다.
트랜잭션이 닫힌 상태에서 지연로딩 프록시 객체에 접근했기 때문에 발생한 문제인데요, 트랜잭션이 닫히기 전 미리 해당 정보를 조회하여 비동기 스레드에 전달하도록 하였습니다.
관련하여 자세한 내용은 역시 [블로그](https://helenason.tistory.com/26)를 통해 확인해주시면 감사하겠습니다 :)

refactor: N+1 문제 해결을 위한 로딩 전략 및 쿼리 변경

---

backend/src/main/java/com/zzang/chongdae/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/zzang/chongdae/member/controller/MemberController.java
backend/src/main/java/com/zzang/chongdae/member/exception/MemberErrorCode.java
backend/src/main/java/com/zzang/chongdae/member/repository/MemberRepository.java
backend/src/main/java/com/zzang/chongdae/member/repository/entity/MemberEntity.java
backend/src/main/java/com/zzang/chongdae/member/service/MemberService.java
backend/src/main/java/com/zzang/chongdae/member/service/dto/NicknameRequest.java
backend/src/main/java/com/zzang/chongdae/member/service/dto/NicknameResponse.java
backend/src/test/java/com/zzang/chongdae/member/integration/MemberIntegrationTest.java
backend/src/test/java/com/zzang/chongdae/member/service/MemberServiceTest.java

close #699 
- 닉네임 변경 기능을 구현했습니다
닉네임 변경 기능을 추가하면서 발견한 문제들을 아래와 같이 해결했는데, 여러분들의 의견이 궁금합니다..! 
1. **닉네임 변경 불가 문제 발견** 
1. `argumentResolver`로 반환한 member는 비영속화 되기 때문 
2. repository 재조회로 member 엔티티 재 영속화로 해결 그러나 select 쿼리 2번 날라가는것이 필연적임
4. argumentResolver에서 레포지토리를 쓰지 않고 memberId dto만 받도록 변경 - 새 이슈 생성 후 처리 예정
2. **동시성 문제 발견**
1.  **같은 회원이 같은 닉네임**으로 변경하는건 막을지 말지 판단이 서지 않음 
1. 일단은 비관적 락을 이용해 막긴 했는데, 안막아도 크게 문제가 되보이진 않음 (의견 구함!!) 
2. **다른 회원이 같은 닉네임으로 변경**할때 유니크 제약 예외 발생
1. 영속성 컨택스트를 주입해서 강제로 flush하게 해서 서비스 로직에서 예외처리하게 함 이 구조에 대해 여러분의 생각은 어떤지 궁금 (아래의 리뷰 코멘트 확인)
2. 서비스 테스트에 롤백 테스트 추가해서 닉네임 중복 시 변경 안되는 테스트 추가
로그인한 회원만 변경이 가능하므로 `ArgumentResolver`로 획득한 `member`를 재활용하여 닉네임을 업데이트하는 계획을 가졌죠. 그리고 서비스 테스트를 돌린 결과 **닉네임이 변경되지 않은 문제가 발생했습니다.**
JPA를 사용하고 있기 때문에`@Transactional`어노테이션이 붙은 메서드가 호출이 종료되면 …

feat: 닉네임 변경 기능 구현

---

backend/src/main/java/com/zzang/chongdae/offering/controller/OfferingReadOnlyWebPageController.java
backend/src/main/resources/templates/detail.html
backend/src/main/resources/templates/index.html

close #714 
* 웹 뷰 페이지 이미지를 불러오지 못해서 수정합니다.
* 개발 image host와 운영 host가 상이하여 `@Values`를 사용하여 설정값을 땡겨왔습니다!
* 타임리프의 입력값 필터링을 적용하기 위해 th:inline="javascript" 를 추가했습니다.

fix: image url 프로파일 별로 설정하도록 수정

---

backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java

close #721 
이전에 중복 참여 방지를 위해 아래 총 네 가지 방안을 적용해본 후 최종적으로 비관적 쓰기 잠금을 적용하였습니다. (관련 PR #673)
성능테스트를 통해 비관적 쓰기 잠금과 낙관적 잠금 간 큰 차이가 없음을 확인하여 안정성이 높은 비관적 쓰기 잠금을 택했었는데요.
사실 중복 참여의 경우 발생 확률이 매우 낮은 케이스입니다. 따라서 이를 위해 모든 참여 API에서 데이터베이스 잠금을 획득하는 것은 불필요하다고 생각하였습니다.
결과적으로는 기존의 비관적 쓰기 잠금을 적용하던 방식에서 낙관적 잠금을 적용하는 방식으로 변경하였습니다.

feat: 중복 참여 방지를 위한 잠금 종류 변경
